# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_generator', '0003_auto_20170126_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(max_length=10000),
        ),
    ]
