# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_generator', '0004_auto_20170131_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='template',
            field=models.CharField(default='[8,8,8,8,0,8,8,8,8]', max_length=20),
        ),
    ]
